### ISSUE TITLE
Support the new WebAuthn keys/sigs

### ISSUE THREAD

**Issue by EnoF** [kadena-io/chainweb-data#171] opened 2023-11-23 11:46 UTC
When making transactions using the new WebAuthn keysets those transactions end up in an error when Chainweb Data attempts to parse it. The error indicates that the sig cannot be parsed, which is due to the new interface necessary for WebAuthn based signatures.

For our kadena internal folks, you can navigate to the webauthn-wallet PoC. Follow the README.md instructions and simply register and then buy a cookie. 

Here is the error message:

```
2023-11-23T11:30:03.517Z [Error] [] Couldn't fetch payload batch for chain: 14
2023-11-23T11:30:03.517Z [Error] [] ApiError {apiError_type = OtherError "Decoding error in payloadWithOutputsBatch: Error in $[0].transactions[0][0]: Error in $.sigs[0]: key \"sig\" not found\nHashes: ( \"dprjb8G8OyOiBgQF_uIhLOyRfXQ1KSqwvcwGwr2-60E\" )", apiError_status = Status {statusCode = 200, statusMessage = "OK"}, apiError_body = "[{\"transactions\":[[\"eyJoYXNoIjoiWG1mRFhfZk1IUFhTQ2k0alFQMnlWU01MOUZPLVBYUENLQ1oySTVyR3k2NCIsInNpZ3MiOlt7ImF1dGhlbnRpY2F0b3JEYXRhIjoibDROVFNkWkJjNGN4MDZSMVE0K0hrSFVra29DRFRpMDF2WklLazd6eUNsd2RBQUFBQUE9PSIsInNpZ25hdHVyZSI6Ik1FUUNJSEJsQ2Y1VmhUbjVrVitvQUhPRGJsU0Y1S0JZV3hleUpzbm8wZEVMSGJ3MEFpQVY1aFlQVHFiczYzZTQ1a2VaTVdPRngxd3J5K1JXRFd5R0dYMGJVZUZqK2c9PSIsImNsaWVudERhdGFKU09OIjoiZXlKMGVYQmxJam9pZDJWaVlYVjBhRzR1WjJWMElpd2lZMmhoYkd4bGJtZGxJam9pV0cxbVJGaGZaazFJVUZoVFEyazBhbEZRTW5sV1UwMU1PVVpQTFZCWVVFTkxRMW95U1RWeVIzazJOQ0lzSW05eWFXZHBiaUk2SW1oMGRIQnpPbHd2WEM5M1pXSmhkWFJvYmkxM1lXeHNaWFF0WkdWdGJ5NTJaWEpqWld3dVlYQndJaXdpWVc1a2NtOXBaRkJoWTJ0aFoyVk9ZVzFsSWpvaVkyOXRMbTFwWTNKdmMyOW1kQzVsYlcxNEluMD0ifV0sImNtZCI6IntcInBheWxvYWRcIjp7XCJleGVjXCI6e1wiY29kZVwiOlwiKG5fNTYwZWVmY2VlNGEwOTBhMjRmMTJkN2NmNjhjZDQ4ZjExZDhkMmJkOS53ZWJhdXRobi13YWxsZXQudHJhbnNmZXIgXFxcInc6WHlKX3BLcmxfbXZzZFlEM19UMEtrRGpiLUZEVWxxemdZeDNYRzcybXQwNDprZXlzLWFueVxcXCIgXFxcImNvb2tpZS1zaG9wXFxcIiA2LjU1KVwiLFwiZGF0YVwiOnt9fX0sXCJtZXRhXCI6e1wiZ2FzTGltaXRcIjoxMDAwLFwiZ2FzUHJpY2VcIjoxZS03LFwic2VuZGVyXCI6XCJjOm5qVjY2cEhCWm9kVmNaWU83enR3TXk2cllteVFRV3YxN29WdDN6RC0tbGdcIixcInR0bFwiOjYwMDAwLFwiY3JlYXRpb25UaW1lXCI6MTcwMDczNjk0MyxcImNoYWluSWRcIjpcIjE0XCJ9LFwibmV0d29ya0lkXCI6XCJmYXN0LWRldmVsb3BtZW50XCIsXCJzaWduZXJzXCI6W3tcInB1YktleVwiOlwiV0VCQVVUSE4tYTUwMTAyMDMyNjIwMDEyMTU4MjA0MGFjZGJhZjliODJlOTJlODliOTBlMDgyNzkwMTQ4ZDQ5ZjJmOWVmYTk0ZTkzMzdjNDFhMGI3NzI5ODEyMmZkMjI1ODIwNGQyMzMyZGVmOTllMGY5ODMxYTUxZWYyNDZkZjBhZmJmYWVhMTFiYWY0ZDM4MWE4Njc3YWQzMTQ5ZjI3YjIwOFwiLFwic2NoZW1lXCI6XCJXZWJBdXRoblwiLFwiY2xpc3RcIjpbe1wibmFtZVwiOlwibl81NjBlZWZjZWU0YTA5MGEyNGYxMmQ3Y2Y2OGNkNDhmMTFkOGQyYmQ5LndlYmF1dGhuLXdhbGxldC5UUkFOU0ZFUlwiLFwiYXJnc1wiOltcInc6WHlKX3BLcmxfbXZzZFlEM19UMEtrRGpiLUZEVWxxemdZeDNYRzcybXQwNDprZXlzLWFueVwiLFwiY29va2llLXNob3BcIiw2LjU1XX0se1wibmFtZVwiOlwibl81NjBlZWZjZWU0YTA5MGEyNGYxMmQ3Y2Y2OGNkNDhmMTFkOGQyYmQ5LndlYmF1dGhuLXdhbGxldC5HQVNfUEFZRVJcIixcImFyZ3NcIjpbXCJ3Olh5Sl9wS3JsX212c2RZRDNfVDBLa0RqYi1GRFVscXpnWXgzWEc3Mm10MDQ6a2V5cy1hbnlcIix7XCJpbnRcIjoxfSwxXX0se1wibmFtZVwiOlwiY29pbi5HQVNcIixcImFyZ3NcIjpbXX1dfV0sXCJub25jZVwiOlwia2pzOm5vbmNlOjE3MDA3MzY5NDM2ODlcIn0ifQ\",\"eyJnYXMiOjg0NywicmVzdWx0Ijp7InN0YXR1cyI6InN1Y2Nlc3MiLCJkYXRhIjoiV3JpdGUgc3VjY2VlZGVkIn0sInJlcUtleSI6IlhtZkRYX2ZNSFBYU0NpNGpRUDJ5VlNNTDlGTy1QWFBDS0NaMkk1ckd5NjQiLCJsb2dzIjoiZXlXQVlrSGNIZkdlOFZsUnFLLWtlVFZmdDNSZXZxallnUVZfb2tPNURBdyIsImV2ZW50cyI6W3sicGFyYW1zIjpbImM6bmpWNjZwSEJab2RWY1pZTzd6dHdNeTZyWW15UVFXdjE3b1Z0M3pELS1sZyIsIms6ZjkwZWY0NjkyN2Y1MDZjNzBiNmE1OGZkMzIyNDUwYTkzNjMxMWRjNmFjOTFmNGVjM2Q4ZWY5NDk2MDhkYmYxZiIsOC40N2UtNV0sIm5hbWUiOiJUUkFOU0ZFUiIsIm1vZHVsZSI6eyJuYW1lc3BhY2UiOm51bGwsIm5hbWUiOiJjb2luIn0sIm1vZHVsZUhhc2giOiJNMWdhYmFrcWtFaV8xTjhkUkt0NHo1bEV2MWt1Q19ueExUbnlEQ3VaSUswIn0seyJwYXJhbXMiOlsidzpYeUpfcEtybF9tdnNkWUQzX1QwS2tEamItRkRVbHF6Z1l4M1hHNzJtdDA0OmtleXMtYW55IiwiY29va2llLXNob3AiLDYuNTVdLCJuYW1lIjoiVFJBTlNGRVIiLCJtb2R1bGUiOnsibmFtZXNwYWNlIjoibl81NjBlZWZjZWU0YTA5MGEyNGYxMmQ3Y2Y2OGNkNDhmMTFkOGQyYmQ5IiwibmFtZSI6IndlYmF1dGhuLXdhbGxldCJ9LCJtb2R1bGVIYXNoIjoiNG5hQUtRZnNqQ3pEQ1hkT0JONjREUnBSbFczbU9PclJkYk9UUjFtdUdlRSJ9LHsicGFyYW1zIjpbImM6bmpWNjZwSEJab2RWY1pZTzd6dHdNeTZyWW15UVFXdjE3b1Z0M3pELS1sZyIsImNvb2tpZS1zaG9wIiw2LjU1XSwibmFtZSI6IlRSQU5TRkVSIiwibW9kdWxlIjp7Im5hbWVzcGFjZSI6bnVsbCwibmFtZSI6ImNvaW4ifSwibW9kdWxlSGFzaCI6Ik0xZ2FiYWtxa0VpXzFOOGRSS3Q0ejVsRXYxa3VDX254TFRueURDdVpJSzAifV0sIm1ldGFEYXRhIjpudWxsLCJjb250aW51YXRpb24iOm51bGwsInR4SWQiOjEwMDUxfQ\"]],\"minerData\":\"eyJhY2NvdW50IjoiazpmOTBlZjQ2OTI3ZjUwNmM3MGI2YTU4ZmQzMjI0NTBhOTM2MzExZGM2YWM5MWY0ZWMzZDhlZjk0OTYwOGRiZjFmIiwicHJlZGljYXRlIjoia2V5cy1hbGwiLCJwdWJsaWMta2V5cyI6WyJmOTBlZjQ2OTI3ZjUwNmM3MGI2YTU4ZmQzMjI0NTBhOTM2MzExZGM2YWM5MWY0ZWMzZDhlZjk0OTYwOGRiZjFmIl19\",\"transactionsHash\":\"KrlXpOlV881bgB2RgN2LBahS6eBB69wxDeKEximAWFU\",\"outputsHash\":\"3ugNDEkvinUW-6COYQrPMZoIEK8uFWVOJL-6O7WHg1A\",\"payloadHash\":\"qY_NhWVh4ZQV6fpV2pSVbC_yi637R48Qw6jT_Vd4vFc\",\"coinbase\":\"eyJnYXMiOjAsInJlc3VsdCI6eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6IldyaXRlIHN1Y2NlZWRlZCJ9LCJyZXFLZXkiOiJJbGxuYTB4YU5HTlFlVll6U1ZwYU5UaE9iamg1UjJOMU9GZGFOVGxFTXpaVlN6Vlpia0ZtVFUxeFgwMGkiLCJsb2dzIjoiVXlHaWl1WnYyVUVDb1ZqZ2ZWWE1vcWlxNFhyNU1BY0VkcEltb3V0NUhjZyIsImV2ZW50cyI6W3sicGFyYW1zIjpbIiIsIms6ZjkwZWY0NjkyN2Y1MDZjNzBiNmE1OGZkMzIyNDUwYTkzNjMxMWRjNmFjOTFmNGVjM2Q4ZWY5NDk2MDhkYmYxZiIsMS4xNTIyNjE1XSwibmFtZSI6IlRSQU5TRkVSIiwibW9kdWxlIjp7Im5hbWVzcGFjZSI6bnVsbCwibmFtZSI6ImNvaW4ifSwibW9kdWxlSGFzaCI6Ik0xZ2FiYWtxa0VpXzFOOGRSS3Q0ejVsRXYxa3VDX254TFRueURDdVpJSzAifV0sIm1ldGFEYXRhIjpudWxsLCJjb250aW51YXRpb24iOm51bGwsInR4SWQiOjEwMDQ5fQ\"}]"}
```

**Comment by enobayram** [comment] 2023-12-11 13:05
We've tried to reproduce this issue with @EnoF, but it seems like it only appeared while running CW-D against an intermediate CW-N commit that was never released. CW-D seems to be handling transactions with webauthn sigs fine with the recently released CW-N 2.22, so I'm closing this issue.

**Closed by enobayram** 2023-12-11 13:05 UTC
